#!/usr/bin/env bash

# This script is idempotent.

set -euxo pipefail

CHAIN=$1
DOMAIN=$2
BRANCH=$3
COMMIT=$4
REVISION="ord-$BRANCH-$COMMIT"

export DEBIAN_FRONTEND=noninteractive

touch ~/.hushlogin

hostnamectl set-hostname $DOMAIN

apt-get install --yes \
  acl \
  clang \
  curl \
  libsqlite3-dev\
  libssl-dev \
  locales-all \
  pkg-config \
  ufw \
  vim

apt-get remove --yes --auto-remove

ufw default allow outgoing
ufw default deny incoming

ufw allow 8080
ufw allow http
ufw allow https
ufw allow ssh

case $CHAIN in
  main)
    COOKIE_FILE_DIR=/var/lib/peercoind
    CSP_ORIGIN=ordinals.com
    ufw allow 9901
    ;;
  regtest)
    COOKIE_FILE_DIR=/var/lib/peercoind/regtest
    CSP_ORIGIN=regtest.ordinals.com
    ufw allow 9903
    ;;
  signet)
    COOKIE_FILE_DIR=/var/lib/peercoind/signet
    CSP_ORIGIN=signet.ordinals.com
    ufw allow 38333
    ;;
  test)
    COOKIE_FILE_DIR=/var/lib/peercoind/testnet3
    CSP_ORIGIN=testnet.ordinals.com
    ufw allow 9903
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

mkdir -p \
  /etc/systemd/system/peercoind.service.d \
  /etc/systemd/system/ord.service.d

printf "[Service]\nEnvironment=CHAIN=%s\nEnvironment=CSP_ORIGIN=%s\n" $CHAIN $CSP_ORIGIN \
  | tee /etc/systemd/system/peercoind.service.d/override.conf \
  > /etc/systemd/system/ord.service.d/override.conf

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sshd -t
systemctl restart sshd

ufw --force enable

if ! which peercoind; then
  ./bin/install-peercoin-linux
fi

peercoind --version

if [[ ! -e ~/.cargo/env ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

source ~/.cargo/env

rustup update stable

cargo build --release
install --backup target/release/ord /usr/local/bin/ord

id --user peercoin || useradd --system peercoin
id --user ord || useradd --system ord

cp deploy/peercoind.service /etc/systemd/system/

mkdir -p /etc/peercoin
cp deploy/peercoin.conf /etc/peercoin/peercoin.conf

if [[ ! -e ~/.peercoin/peercoin.conf ]]; then
  mkdir -p ~/.peercoin
  ln -s /etc/peercoin/peercoin.conf ~/.peercoin/peercoin.conf
fi

systemctl daemon-reload
systemctl enable peercoind
systemctl restart peercoind

while [[ ! -f $COOKIE_FILE_DIR/.cookie ]]; do
  echo "Waiting for peercoind…"
  sleep 1
done

setfacl -m ord:x /var/lib/peercoind
setfacl -m ord:x $COOKIE_FILE_DIR
setfacl -dm ord:r $COOKIE_FILE_DIR
setfacl -m ord:r $COOKIE_FILE_DIR/.cookie

journalctl --unit ord --vacuum-time 1s

cp deploy/ord.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable ord
systemctl restart ord

while ! curl --fail https://$DOMAIN/status > /dev/null; do
  echo "Waiting for ord at https://$DOMAIN/status…"
  sleep 1
done
